local L = LibStub("AceLocale-3.0"):NewLocale("ChonkyBirb", "deDE", false)
if not L then return end

-- Resource names
L["Health"] = "Gesundheit"
L["Mana"] = "Mana"
L["Rage"] = "Wut"
L["Energy"] = "Energie"
L["Focus"] = "Fokus"
L["Runic Power"] = "Runenmacht"
L["Runes"] = "Runen"
L["Astral Power"] = "Astrale Macht"
L["Soul Shards"] = "Seelensplitter"
L["Soul Fragments"] = "Seelenfragmente"
L["Holy Power"] = "Heilige Kraft"
L["Chi"] = "Chi"
L["Insanity"] = "Wahnsinn"
L["Maelstrom"] = "Mahlstrom"
L["Fury"] = "Jähzorn"
L["Combo Points"] = "Combopunkte"
L["Arcane Charges"] = "Arkane Aufladungen"
L["Essence"] = "Essenz"
L["Stagger"] = "Staffelung"
L["Stagger Colors"] = "Staffelungsfarben"
L["Light"] = "Leicht"
L["Moderate"] = "Moderat"
L["Heavy"] = "Schwer"
L["Maelstrom Weapon"] = "Waffe des Mahlstroms"

-- Tabs / sections
L["General"] = "Allgemein"
L["Bars"] = "Leisten"
L["Profiles"] = "Profile"

-- General options
L["Unlock"] = "Entsperren"
L["Lock"] = "Sperren"
L["Unlock bars to drag and position them; every bar is shown while unlocked."] = "Entsperrt die Leisten, um sie zu verschieben und zu platzieren; solange sie entsperrt sind, werden alle Leisten angezeigt."
L["Link bars"] = "Leisten verknüpfen"
L["Drag one bar and they all move together."] = "Eine Leiste ziehen, und alle bewegen sich gemeinsam."
L["Move group"] = "Gruppe verschieben"
L["Bars unlocked — drag or use the sliders to move them."] = "Leisten entsperrt — ziehen oder die Schieberegler zum Verschieben verwenden."

-- Global defaults (font / border / background for all bars; per-bar settings override)
L["Default appearance (all bars)"] = "Standardaussehen (alle Leisten)"
L["Default Font"] = "Standardschriftart"
L["Default Border"] = "Standardrand"
L["Default Background"] = "Standardhintergrund"
L["Reset to default"] = "Auf Standard zurücksetzen"
L["Clear this bar's border & background overrides so they follow the global defaults."] = "Entfernt die eigenen Rand- und Hintergrundeinstellungen dieser Leiste, sodass sie den globalen Standards folgt."
L["Clear this text's font overrides so it follows the global default font."] = "Entfernt die eigene Schriftart dieses Textes, sodass er der globalen Standardschriftart folgt."
L["Strata"] = "Ebene"
L["Display layer. A bar on a higher strata fully covers a lower one (text included)."] = "Anzeigeebene. Eine Leiste auf einer höheren Ebene verdeckt eine niedrigere vollständig (einschließlich Text)."
L["Copy settings from"] = "Einstellungen kopieren von"
L["Copy another bar's look + position onto this one. Tags, visibility and the enabled state are kept."] = "Kopiert Aussehen und Position einer anderen Leiste auf diese. Tags, Sichtbarkeit und Aktivierungsstatus bleiben erhalten."
L["Cast Prediction"] = "Zaubervorhersage"
L["Predict cast generation"] = "Erzeugte Ressource vorhersagen"
L["While casting, preview the resource the cast will generate as a ghost segment."] = "Zeigt während des Zauberns die erzeugte Ressource als Geistersegment an."
L["Prediction Color"] = "Vorhersagefarbe"
L["Color and opacity of the cast-prediction ghost."] = "Farbe und Deckkraft des Vorhersage-Geistersegments."
L["Bar Color + Opacity"] = "Leistenfarbe und Deckkraft"
L["Custom Color"] = "Eigene Farbe"
L["Opacity"] = "Deckkraft"

-- Value markers
L["Markers"] = "Markierungen"
L["Marker"] = "Markierung"
L["Add Marker"] = "Markierung hinzufügen"
L["Value"] = "Wert"
L["Position of the marker, in resource value."] = "Position der Markierung als Ressourcenwert."
L["Marker thickness."] = "Dicke der Markierung."
L["Bar Height"] = "Leistenhöhe"
L["Custom Height"] = "Eigene Höhe"
L["Marker Color"] = "Markierungsfarbe"
L["Marker color and opacity."] = "Farbe und Deckkraft der Markierung."
L["All spells are known"] = "Alle Zauber sind bekannt"
L["At least one spell is known"] = "Mindestens ein Zauber ist bekannt"
L["No spell is known"] = "Kein Zauber ist bekannt"
L["Add Spell"] = "Zauber hinzufügen"
L["Spell ID, name, or a shift-clicked talent link."] = "Zauber-ID, Name oder ein per Umschalt-Klick eingefügter Talentlink."
L["Marker Type"] = "Markierungstyp"
L["Static Value"] = "Fester Wert"
L["Spell Cost"] = "Zauberkosten"
L["Spell"] = "Zauber"
L["Count"] = "Anzahl"
L["Places markers at 1x, 2x, 3x... the spell's cost."] = "Setzt Markierungen bei 1x, 2x, 3x… der Zauberkosten."
L["Cost:"] = "Kosten:"
L["No flat cost found for this bar's resource."] = "Keine festen Kosten für die Ressource dieser Leiste gefunden."

-- Per-bar options
L["Enabled"] = "Aktiviert"
L["Width"] = "Breite"
L["Height"] = "Höhe"
L["Position"] = "Position"
L["Position X"] = "Position X"
L["Position Y"] = "Position Y"
L["Scale"] = "Skalierung"
L["Bar Texture"] = "Leistentextur"
L["Bar Color"] = "Leistenfarbe"
L["Background Texture"] = "Hintergrundtextur"
L["Background Color"] = "Hintergrundfarbe"
L["Border Texture"] = "Randtextur"
L["Border Size"] = "Randgröße"
L["Border Color"] = "Randfarbe"
L["Fill Direction"] = "Füllrichtung"
L["Segment Spacing"] = "Segmentabstand"
L["Gap between segments, in pixels."] = "Abstand zwischen den Segmenten in Pixeln."
L["Inactive Segments"] = "Inaktive Segmente"
L["Inactive Segment Color"] = "Farbe inaktiver Segmente"
L["Color + Opacity"] = "Farbe und Deckkraft"
L["Recharge Display"] = "Aufladungsanzeige"
L["Recharge Color"] = "Aufladungsfarbe"

-- Color by percent
L["Color Mode"] = "Farbmodus"
L["Static"] = "Statisch"
L["By Percent"] = "Nach Prozent"
L["The bar recolors based on its fill percentage."] = "Die Leiste färbt sich nach ihrem Füllstand in Prozent."
L["Color by percent"] = "Farbe nach Prozent"
L["Curve Type"] = "Kurventyp"
L["Sharp Steps"] = "Harte Stufen"
L["Smooth Gradient"] = "Weicher Verlauf"
L["Add Color"] = "Farbe hinzufügen"
L["Color"] = "Farbe"
L["Font"] = "Schriftart"
L["Font Size"] = "Schriftgröße"
L["Outline"] = "Kontur"
L["Font Color"] = "Schriftfarbe"

-- Fill directions
L["Left to Right"] = "Von links nach rechts"
L["Right to Left"] = "Von rechts nach links"
L["Bottom to Top"] = "Von unten nach oben"
L["Top to Bottom"] = "Von oben nach unten"

-- Font outline / shadow
L["None"] = "Keine"
L["Thick Outline"] = "Dicke Kontur"
L["Shadow"] = "Schatten"
L["Shadow Color"] = "Schattenfarbe"
L["Shadow X"] = "Schatten X"
L["Shadow Y"] = "Schatten Y"

-- Text fields
L["Text"] = "Text"
L["Texts"] = "Texte"
L["Add Text"] = "Text hinzufügen"
L["Remove"] = "Entfernen"
L["Anchor"] = "Verankerung"
L["X"] = "X"
L["Y"] = "Y"
L["Tags"] = "Tags"

-- Text tags: bar-relative, name + mouseover description
L["Current Value"] = "Aktueller Wert"
L["Max Value"] = "Maximalwert"
L["Current / Max"] = "Aktuell / Max"
L["Percent"] = "Prozent"
L["Deficit"] = "Fehlend"
L["Current (full)"] = "Aktuell (voll)"
L["Max (full)"] = "Max (voll)"
L["Current / Max (full)"] = "Aktuell / Max (voll)"
L["Resource Name"] = "Ressourcenname"
L["Current value of this bar's resource (short form)."] = "Aktueller Wert der Ressource dieser Leiste (Kurzform)."
L["Maximum value of this bar's resource (short form)."] = "Maximalwert der Ressource dieser Leiste (Kurzform)."
L["Current and maximum, shown as cur/max (short form)."] = "Aktueller und maximaler Wert als akt/max (Kurzform)."
L["Current value as a percentage (0-100%)."] = "Aktueller Wert in Prozent (0-100%)."
L["Missing amount (max minus current)."] = "Fehlender Betrag (Max minus Aktuell)."
L["Current value, full number (not abbreviated)."] = "Aktueller Wert als volle Zahl (nicht abgekürzt)."
L["Maximum value, full number (not abbreviated)."] = "Maximalwert als volle Zahl (nicht abgekürzt)."
L["Current and maximum as cur/max, full numbers."] = "Aktueller und maximaler Wert als akt/max, volle Zahlen."
L["Name of the resource (e.g. Energy)."] = "Name der Ressource (z. B. Energie)."

-- Text tags: absolute class resources
L["Current number of combo points."] = "Aktuelle Anzahl an Combopunkten."
L["Current number of soul shards."] = "Aktuelle Anzahl an Seelensplittern."
L["Current holy power."] = "Aktuelle Heilige Kraft."
L["Current number of Chi."] = "Aktuelle Anzahl an Chi."
L["Current number of arcane charges."] = "Aktuelle Anzahl an Arkanen Aufladungen."
L["Current number of ready runes."] = "Aktuelle Anzahl bereiter Runen."
L["Current runic power."] = "Aktuelle Runenmacht."
L["Current number of essence."] = "Aktuelle Essenz."
L["Current insanity."] = "Aktueller Wahnsinn."
L["Current maelstrom."] = "Aktueller Mahlstrom."
L["Current astral power."] = "Aktuelle Astrale Macht."
L["Current fury."] = "Aktueller Jähzorn."
L["Current mana."] = "Aktuelles Mana."

-- Visibility
L["Visibility"] = "Sichtbarkeit"
L["Show"] = "Anzeigen"
L["Always"] = "Immer"
L["Automatic"] = "Automatisch"
L["Never"] = "Nie"
L["Custom"] = "Benutzerdefiniert"
L["Automatic shows the bar only while its resource is relevant (forms, spec)."] = "Automatisch zeigt die Leiste nur, wenn ihre Ressource relevant ist (Gestalt, Spezialisierung)."
L["The bar shows when any checked condition is true."] = "Die Leiste wird angezeigt, sobald eine der angehakten Bedingungen zutrifft."
L["Auto-hide all bars while"] = "Alle Leisten automatisch ausblenden"
L["In Vehicle"] = "Im Fahrzeug"
L["Pet Battle"] = "Im Haustierkampf"
L["Blizzard frames"] = "Blizzard-Fenster"
L["Hide Blizzard Resource Bars"] = "Blizzard-Ressourcenleisten ausblenden"
L["Hide Blizzard's detached resource bars."] = "Blendet die losgelösten Ressourcenleisten von Blizzard aus."

-- Visibility condition sections
L["Combat & Target"] = "Kampf & Ziel"
L["PvP"] = "PvP"
L["Mount"] = "Reittier"
L["Druid Forms"] = "Druidengestalten"

-- Visibility conditions
L["In Combat"] = "Im Kampf"
L["Has Target"] = "Ziel vorhanden"
L["Hostile Target"] = "Feindliches Ziel"
L["Attackable Target"] = "Angreifbares Ziel"
L["Friendly Target"] = "Freundliches Ziel"
L["Group"] = "Gruppe"
L["Instance"] = "Instanz"
L["In Any Group"] = "In einer Gruppe"
L["In Raid Group"] = "In einer Schlachtzugsgruppe"
L["In Instance"] = "In einer Instanz"
L["In Dungeon"] = "Im Dungeon"
L["In Raid"] = "Im Schlachtzug"
L["In Battleground"] = "Auf dem Schlachtfeld"
L["In Arena"] = "In der Arena"
L["PvP Flagged"] = "PvP aktiv"
L["War Mode"] = "Kriegsmodus"
L["Mounted"] = "Beritten"
L["Flying"] = "Im Flug"
L["Cat Form"] = "Katzengestalt"
L["Bear Form"] = "Bärengestalt"
L["Moonkin Form"] = "Mondkingestalt"
L["Travel Form (Stag)"] = "Reisegestalt (Hirsch)"
L["Aquatic Form"] = "Wassergestalt"
L["Flight Form"] = "Fluggestalt"
L["Swift Flight Form"] = "Epische Fluggestalt"
L["Travel Form (Any)"] = "Reisegestalt (alle)"
L["Humanoid Form"] = "Humanoide Gestalt"
