local L = LibStub("AceLocale-3.0"):NewLocale("ChonkyBirb", "esES", false)
if not L then return end

-- Resource names
L["Health"] = "Salud"
L["Mana"] = "Maná"
L["Rage"] = "Ira"
L["Energy"] = "Energía"
L["Focus"] = "Enfoque"
L["Runic Power"] = "Poder rúnico"
L["Runes"] = "Runas"
L["Astral Power"] = "Poder Astral"
L["Soul Shards"] = "Fragmentos de alma"
L["Soul Fragments"] = "Trozos de alma"
L["Holy Power"] = "Poder sagrado"
L["Chi"] = "Chi"
L["Insanity"] = "Demencia"
L["Maelstrom"] = "Vorágine"
L["Fury"] = "Furia"
L["Combo Points"] = "Puntos de combo"
L["Arcane Charges"] = "Cargas Arcanas"
L["Essence"] = "Esencia"
L["Stagger"] = "Aplazar"
L["Stagger Colors"] = "Colores de Aplazar"
L["Light"] = "Leve"
L["Moderate"] = "Moderado"
L["Heavy"] = "Severo"
L["Maelstrom Weapon"] = "Arma vorágine"

-- Tabs / sections
L["General"] = "General"
L["Bars"] = "Barras"
L["Profiles"] = "Perfiles"

-- General options
L["Unlock"] = "Desbloquear"
L["Lock"] = "Bloquear"
L["Unlock bars to drag and position them; every bar is shown while unlocked."] = "Desbloquea las barras para arrastrarlas y colocarlas; mientras estén desbloqueadas se muestran todas."
L["Link bars"] = "Enlazar barras"
L["Drag one bar and they all move together."] = "Arrastra una barra y todas se mueven juntas."
L["Move group"] = "Mover grupo"
L["Bars unlocked — drag or use the sliders to move them."] = "Barras desbloqueadas — arrástralas o usa los deslizadores para moverlas."

-- Global defaults (font / border / background for all bars; per-bar settings override)
L["Default appearance (all bars)"] = "Apariencia predeterminada (todas las barras)"
L["Default Font"] = "Fuente predeterminada"
L["Default Border"] = "Borde predeterminado"
L["Default Background"] = "Fondo predeterminado"
L["Reset to default"] = "Restablecer valor predeterminado"
L["Clear this bar's border & background overrides so they follow the global defaults."] = "Elimina el borde y el fondo personalizados de esta barra para que siga los valores globales."
L["Clear this text's font overrides so it follows the global default font."] = "Elimina la fuente personalizada de este texto para que siga la fuente global."
L["Strata"] = "Estrato"
L["Display layer. A bar on a higher strata fully covers a lower one (text included)."] = "Capa de visualización. Una barra en un estrato superior cubre por completo a una inferior (texto incluido)."
L["Copy settings from"] = "Copiar ajustes de"
L["Copy another bar's look + position onto this one. Tags, visibility and the enabled state are kept."] = "Copia el aspecto y la posición de otra barra en esta. Se conservan las etiquetas, la visibilidad y el estado de activación."
L["Cast Prediction"] = "Predicción de lanzamiento"
L["Predict cast generation"] = "Predecir el recurso generado"
L["While casting, preview the resource the cast will generate as a ghost segment."] = "Durante el lanzamiento, muestra como segmento fantasma el recurso que generará el hechizo."
L["Prediction Color"] = "Color de la predicción"
L["Color and opacity of the cast-prediction ghost."] = "Color y opacidad del segmento fantasma de predicción."
L["Bar Color + Opacity"] = "Color y opacidad de la barra"
L["Custom Color"] = "Color personalizado"
L["Opacity"] = "Opacidad"

-- Value markers
L["Markers"] = "Marcadores"
L["Marker"] = "Marcador"
L["Add Marker"] = "Añadir marcador"
L["Value"] = "Valor"
L["Position of the marker, in resource value."] = "Posición del marcador, en valor de recurso."
L["Marker thickness."] = "Grosor del marcador."
L["Bar Height"] = "Altura de la barra"
L["Custom Height"] = "Altura personalizada"
L["Marker Color"] = "Color del marcador"
L["Marker color and opacity."] = "Color y opacidad del marcador."
L["All spells are known"] = "Se conocen todos los hechizos"
L["At least one spell is known"] = "Se conoce al menos un hechizo"
L["No spell is known"] = "No se conoce ningún hechizo"
L["Add Spell"] = "Añadir hechizo"
L["Spell ID, name, or a shift-clicked talent link."] = "ID del hechizo, nombre o un enlace de talento insertado con Mayús+clic."
L["Marker Type"] = "Tipo de marcador"
L["Static Value"] = "Valor fijo"
L["Spell Cost"] = "Coste de hechizo"
L["Spell"] = "Hechizo"
L["Count"] = "Cantidad"
L["Places markers at 1x, 2x, 3x... the spell's cost."] = "Coloca marcadores en 1x, 2x, 3x… el coste del hechizo."
L["Cost:"] = "Coste:"
L["No flat cost found for this bar's resource."] = "No se encontró un coste fijo para el recurso de esta barra."

-- Per-bar options
L["Enabled"] = "Activada"
L["Width"] = "Anchura"
L["Height"] = "Altura"
L["Position"] = "Posición"
L["Position X"] = "Posición X"
L["Position Y"] = "Posición Y"
L["Scale"] = "Escala"
L["Bar Texture"] = "Textura de la barra"
L["Bar Color"] = "Color de la barra"
L["Background Texture"] = "Textura del fondo"
L["Background Color"] = "Color del fondo"
L["Border Texture"] = "Textura del borde"
L["Border Size"] = "Tamaño del borde"
L["Border Color"] = "Color del borde"
L["Fill Direction"] = "Dirección de llenado"
L["Segment Spacing"] = "Separación de segmentos"
L["Gap between segments, in pixels."] = "Espacio entre segmentos, en píxeles."
L["Inactive Segments"] = "Segmentos inactivos"
L["Inactive Segment Color"] = "Color de segmentos inactivos"
L["Color + Opacity"] = "Color y opacidad"
L["Recharge Display"] = "Indicador de recarga"
L["Recharge Color"] = "Color de recarga"

-- Color by percent
L["Color Mode"] = "Modo de color"
L["Static"] = "Fijo"
L["By Percent"] = "Por porcentaje"
L["The bar recolors based on its fill percentage."] = "La barra cambia de color según su porcentaje de llenado."
L["Color by percent"] = "Color por porcentaje"
L["Curve Type"] = "Tipo de curva"
L["Sharp Steps"] = "Escalones marcados"
L["Smooth Gradient"] = "Degradado suave"
L["Add Color"] = "Añadir color"
L["Color"] = "Color"
L["Font"] = "Fuente"
L["Font Size"] = "Tamaño de fuente"
L["Outline"] = "Contorno"
L["Font Color"] = "Color de fuente"

-- Fill directions
L["Left to Right"] = "De izquierda a derecha"
L["Right to Left"] = "De derecha a izquierda"
L["Bottom to Top"] = "De abajo arriba"
L["Top to Bottom"] = "De arriba abajo"

-- Font outline / shadow
L["None"] = "Ninguno"
L["Thick Outline"] = "Contorno grueso"
L["Shadow"] = "Sombra"
L["Shadow Color"] = "Color de la sombra"
L["Shadow X"] = "Sombra X"
L["Shadow Y"] = "Sombra Y"

-- Text fields
L["Text"] = "Texto"
L["Texts"] = "Textos"
L["Add Text"] = "Añadir texto"
L["Remove"] = "Eliminar"
L["Anchor"] = "Anclaje"
L["X"] = "X"
L["Y"] = "Y"
L["Tags"] = "Etiquetas"

-- Text tags: bar-relative, name + mouseover description
L["Current Value"] = "Valor actual"
L["Max Value"] = "Valor máximo"
L["Current / Max"] = "Actual / Máx."
L["Percent"] = "Porcentaje"
L["Deficit"] = "Déficit"
L["Current (full)"] = "Actual (completo)"
L["Max (full)"] = "Máx. (completo)"
L["Current / Max (full)"] = "Actual / Máx. (completos)"
L["Resource Name"] = "Nombre del recurso"
L["Current value of this bar's resource (short form)."] = "Valor actual del recurso de esta barra (abreviado)."
L["Maximum value of this bar's resource (short form)."] = "Valor máximo del recurso de esta barra (abreviado)."
L["Current and maximum, shown as cur/max (short form)."] = "Valor actual y máximo, como act/máx (abreviados)."
L["Current value as a percentage (0-100%)."] = "Valor actual en porcentaje (0-100%)."
L["Missing amount (max minus current)."] = "Cantidad que falta (máximo menos actual)."
L["Current value, full number (not abbreviated)."] = "Valor actual, número completo (sin abreviar)."
L["Maximum value, full number (not abbreviated)."] = "Valor máximo, número completo (sin abreviar)."
L["Current and maximum as cur/max, full numbers."] = "Valor actual y máximo como act/máx, números completos."
L["Name of the resource (e.g. Energy)."] = "Nombre del recurso (p. ej. Energía)."

-- Text tags: absolute class resources
L["Current number of combo points."] = "Número actual de puntos de combo."
L["Current number of soul shards."] = "Número actual de fragmentos de alma."
L["Current holy power."] = "Poder sagrado actual."
L["Current number of Chi."] = "Número actual de Chi."
L["Current number of arcane charges."] = "Número actual de cargas arcanas."
L["Current number of ready runes."] = "Número actual de runas disponibles."
L["Current runic power."] = "Poder rúnico actual."
L["Current number of essence."] = "Esencia actual."
L["Current insanity."] = "Demencia actual."
L["Current maelstrom."] = "Vorágine actual."
L["Current astral power."] = "Poder astral actual."
L["Current fury."] = "Furia actual."
L["Current mana."] = "Maná actual."

-- Visibility
L["Visibility"] = "Visibilidad"
L["Show"] = "Mostrar"
L["Always"] = "Siempre"
L["Automatic"] = "Automático"
L["Never"] = "Nunca"
L["Custom"] = "Personalizado"
L["Automatic shows the bar only while its resource is relevant (forms, spec)."] = "Automático muestra la barra solo cuando su recurso es relevante (formas, especialización)."
L["The bar shows when any checked condition is true."] = "La barra se muestra cuando se cumple cualquiera de las condiciones marcadas."
L["Auto-hide all bars while"] = "Ocultar todas las barras automáticamente"
L["In Vehicle"] = "En un vehículo"
L["Pet Battle"] = "En duelo de mascotas"
L["Blizzard frames"] = "Marcos de Blizzard"
L["Hide Blizzard Resource Bars"] = "Ocultar las barras de recursos de Blizzard"
L["Hide Blizzard's detached resource bars."] = "Oculta las barras de recursos independientes de Blizzard."

-- Visibility condition sections
L["Combat & Target"] = "Combate y objetivo"
L["PvP"] = "JcJ"
L["Mount"] = "Montura"
L["Druid Forms"] = "Formas de druida"

-- Visibility conditions
L["In Combat"] = "En combate"
L["Has Target"] = "Con objetivo"
L["Hostile Target"] = "Objetivo hostil"
L["Attackable Target"] = "Objetivo atacable"
L["Friendly Target"] = "Objetivo amistoso"
L["Group"] = "Grupo"
L["Instance"] = "Instancia"
L["In Any Group"] = "En cualquier grupo"
L["In Raid Group"] = "En grupo de banda"
L["In Instance"] = "En una instancia"
L["In Dungeon"] = "En una mazmorra"
L["In Raid"] = "En una banda"
L["In Battleground"] = "En un campo de batalla"
L["In Arena"] = "En una arena"
L["PvP Flagged"] = "JcJ activado"
L["War Mode"] = "Modo Guerra"
L["Mounted"] = "Montado"
L["Flying"] = "Volando"
L["Cat Form"] = "Forma felina"
L["Bear Form"] = "Forma de oso"
L["Moonkin Form"] = "Forma de lechúcico lunar"
L["Travel Form (Stag)"] = "Forma de viaje (ciervo)"
L["Aquatic Form"] = "Forma acuática"
L["Flight Form"] = "Forma de vuelo"
L["Swift Flight Form"] = "Forma voladora épica"
L["Travel Form (Any)"] = "Forma de viaje (cualquiera)"
L["Humanoid Form"] = "Forma humanoide"
