local L = LibStub("AceLocale-3.0"):NewLocale("ChonkyBirb", "frFR", false)
if not L then return end

-- Resource names
L["Health"] = "Vie"
L["Mana"] = "Mana"
L["Rage"] = "Rage"
L["Energy"] = "Énergie"
L["Focus"] = "Focalisation"
L["Runic Power"] = "Puissance runique"
L["Runes"] = "Runes"
L["Astral Power"] = "Puissance astrale"
L["Soul Shards"] = "Éclats d'âme"
L["Soul Fragments"] = "Fragments d'âme"
L["Holy Power"] = "Puissance sacrée"
L["Chi"] = "Chi"
L["Insanity"] = "Insanité"
L["Maelstrom"] = "Maelström"
L["Fury"] = "Fureur"
L["Combo Points"] = "Points de combo"
L["Arcane Charges"] = "Charges arcaniques"
L["Essence"] = "Essence"
L["Stagger"] = "Report"
L["Stagger Colors"] = "Couleurs du Report"
L["Light"] = "Mineur"
L["Moderate"] = "Modéré"
L["Heavy"] = "Majeur"
L["Maelstrom Weapon"] = "Arme du Maelström"

-- Tabs / sections
L["General"] = "Général"
L["Bars"] = "Barres"
L["Profiles"] = "Profils"

-- General options
L["Unlock"] = "Déverrouiller"
L["Lock"] = "Verrouiller"
L["Unlock bars to drag and position them; every bar is shown while unlocked."] = "Déverrouille les barres pour les déplacer à la souris ; toutes les barres sont affichées tant qu'elles sont déverrouillées."
L["Link bars"] = "Lier les barres"
L["Drag one bar and they all move together."] = "Déplacez une barre et toutes suivent."
L["Move group"] = "Déplacer le groupe"
L["Bars unlocked — drag or use the sliders to move them."] = "Barres déverrouillées — déplacez-les à la souris ou avec les curseurs."

-- Global defaults (font / border / background for all bars; per-bar settings override)
L["Default appearance (all bars)"] = "Apparence par défaut (toutes les barres)"
L["Default Font"] = "Police par défaut"
L["Default Border"] = "Bordure par défaut"
L["Default Background"] = "Fond par défaut"
L["Reset to default"] = "Rétablir la valeur par défaut"
L["Clear this bar's border & background overrides so they follow the global defaults."] = "Efface la bordure et le fond personnalisés de cette barre pour qu'elle suive les réglages globaux."
L["Clear this text's font overrides so it follows the global default font."] = "Efface la police personnalisée de ce texte pour qu'il suive la police globale."
L["Strata"] = "Strate"
L["Display layer. A bar on a higher strata fully covers a lower one (text included)."] = "Couche d'affichage. Une barre sur une strate supérieure recouvre entièrement une barre inférieure (texte compris)."
L["Copy settings from"] = "Copier les réglages de"
L["Copy another bar's look + position onto this one. Tags, visibility and the enabled state are kept."] = "Copie l'apparence et la position d'une autre barre sur celle-ci. Les tags, la visibilité et l'état activé sont conservés."
L["Cast Prediction"] = "Prédiction de sort"
L["Predict cast generation"] = "Prédire la ressource générée"
L["While casting, preview the resource the cast will generate as a ghost segment."] = "Pendant une incantation, affiche en fantôme la ressource que le sort va générer."
L["Prediction Color"] = "Couleur de la prédiction"
L["Color and opacity of the cast-prediction ghost."] = "Couleur et opacité du fantôme de prédiction."
L["Bar Color + Opacity"] = "Couleur et opacité de la barre"
L["Custom Color"] = "Couleur personnalisée"
L["Opacity"] = "Opacité"

-- Value markers
L["Markers"] = "Repères"
L["Marker"] = "Repère"
L["Add Marker"] = "Ajouter un repère"
L["Value"] = "Valeur"
L["Position of the marker, in resource value."] = "Position du repère, en valeur de ressource."
L["Marker thickness."] = "Épaisseur du repère."
L["Bar Height"] = "Hauteur de la barre"
L["Custom Height"] = "Hauteur personnalisée"
L["Marker Color"] = "Couleur du repère"
L["Marker color and opacity."] = "Couleur et opacité du repère."
L["All spells are known"] = "Tous les sorts sont connus"
L["At least one spell is known"] = "Au moins un sort est connu"
L["No spell is known"] = "Aucun sort n'est connu"
L["Add Spell"] = "Ajouter un sort"
L["Spell ID, name, or a shift-clicked talent link."] = "ID de sort, nom, ou lien de talent inséré par Maj-clic."
L["Marker Type"] = "Type de repère"
L["Static Value"] = "Valeur fixe"
L["Spell Cost"] = "Coût d'un sort"
L["Spell"] = "Sort"
L["Count"] = "Nombre"
L["Places markers at 1x, 2x, 3x... the spell's cost."] = "Place des repères à 1x, 2x, 3x… le coût du sort."
L["Cost:"] = "Coût :"
L["No flat cost found for this bar's resource."] = "Aucun coût fixe trouvé pour la ressource de cette barre."

-- Per-bar options
L["Enabled"] = "Activée"
L["Width"] = "Largeur"
L["Height"] = "Hauteur"
L["Position"] = "Position"
L["Position X"] = "Position X"
L["Position Y"] = "Position Y"
L["Scale"] = "Échelle"
L["Bar Texture"] = "Texture de la barre"
L["Bar Color"] = "Couleur de la barre"
L["Background Texture"] = "Texture du fond"
L["Background Color"] = "Couleur du fond"
L["Border Texture"] = "Texture de la bordure"
L["Border Size"] = "Taille de la bordure"
L["Border Color"] = "Couleur de la bordure"
L["Fill Direction"] = "Sens de remplissage"
L["Segment Spacing"] = "Espacement des segments"
L["Gap between segments, in pixels."] = "Espace entre les segments, en pixels."
L["Inactive Segments"] = "Segments inactifs"
L["Inactive Segment Color"] = "Couleur des segments inactifs"
L["Color + Opacity"] = "Couleur et opacité"
L["Recharge Display"] = "Affichage de la recharge"
L["Recharge Color"] = "Couleur de la recharge"

-- Color by percent
L["Color Mode"] = "Mode de couleur"
L["Static"] = "Fixe"
L["By Percent"] = "Par pourcentage"
L["The bar recolors based on its fill percentage."] = "La barre change de couleur selon son pourcentage de remplissage."
L["Color by percent"] = "Couleur par pourcentage"
L["Curve Type"] = "Type de courbe"
L["Sharp Steps"] = "Paliers nets"
L["Smooth Gradient"] = "Dégradé fluide"
L["Add Color"] = "Ajouter une couleur"
L["Color"] = "Couleur"
L["Font"] = "Police"
L["Font Size"] = "Taille de la police"
L["Outline"] = "Contour"
L["Font Color"] = "Couleur de la police"

-- Fill directions
L["Left to Right"] = "De gauche à droite"
L["Right to Left"] = "De droite à gauche"
L["Bottom to Top"] = "De bas en haut"
L["Top to Bottom"] = "De haut en bas"

-- Font outline / shadow
L["None"] = "Aucun"
L["Thick Outline"] = "Contour épais"
L["Shadow"] = "Ombre"
L["Shadow Color"] = "Couleur de l'ombre"
L["Shadow X"] = "Ombre X"
L["Shadow Y"] = "Ombre Y"

-- Text fields
L["Text"] = "Texte"
L["Texts"] = "Textes"
L["Add Text"] = "Ajouter un texte"
L["Remove"] = "Supprimer"
L["Anchor"] = "Ancrage"
L["X"] = "X"
L["Y"] = "Y"
L["Tags"] = "Tags"

-- Text tags: bar-relative, name + mouseover description
L["Current Value"] = "Valeur actuelle"
L["Max Value"] = "Valeur maximale"
L["Current / Max"] = "Actuelle / Max"
L["Percent"] = "Pourcentage"
L["Deficit"] = "Déficit"
L["Current (full)"] = "Actuelle (complète)"
L["Max (full)"] = "Max (complète)"
L["Current / Max (full)"] = "Actuelle / Max (complètes)"
L["Resource Name"] = "Nom de la ressource"
L["Current value of this bar's resource (short form)."] = "Valeur actuelle de la ressource de cette barre (abrégée)."
L["Maximum value of this bar's resource (short form)."] = "Valeur maximale de la ressource de cette barre (abrégée)."
L["Current and maximum, shown as cur/max (short form)."] = "Valeur actuelle et maximale, sous la forme act/max (abrégées)."
L["Current value as a percentage (0-100%)."] = "Valeur actuelle en pourcentage (0-100 %)."
L["Missing amount (max minus current)."] = "Quantité manquante (max moins actuelle)."
L["Current value, full number (not abbreviated)."] = "Valeur actuelle, nombre complet (non abrégé)."
L["Maximum value, full number (not abbreviated)."] = "Valeur maximale, nombre complet (non abrégé)."
L["Current and maximum as cur/max, full numbers."] = "Valeur actuelle et maximale sous la forme act/max, nombres complets."
L["Name of the resource (e.g. Energy)."] = "Nom de la ressource (ex. Énergie)."

-- Text tags: absolute class resources
L["Current number of combo points."] = "Nombre actuel de points de combo."
L["Current number of soul shards."] = "Nombre actuel d'éclats d'âme."
L["Current holy power."] = "Puissance sacrée actuelle."
L["Current number of Chi."] = "Nombre actuel de Chi."
L["Current number of arcane charges."] = "Nombre actuel de charges arcaniques."
L["Current number of ready runes."] = "Nombre actuel de runes disponibles."
L["Current runic power."] = "Puissance runique actuelle."
L["Current number of essence."] = "Essence actuelle."
L["Current insanity."] = "Insanité actuelle."
L["Current maelstrom."] = "Maelström actuel."
L["Current astral power."] = "Puissance astrale actuelle."
L["Current fury."] = "Fureur actuelle."
L["Current mana."] = "Mana actuel."

-- Visibility
L["Visibility"] = "Visibilité"
L["Show"] = "Afficher"
L["Always"] = "Toujours"
L["Automatic"] = "Automatique"
L["Never"] = "Jamais"
L["Custom"] = "Personnalisé"
L["Automatic shows the bar only while its resource is relevant (forms, spec)."] = "Automatique n'affiche la barre que lorsque sa ressource est pertinente (formes, spécialisation)."
L["The bar shows when any checked condition is true."] = "La barre s'affiche dès qu'une condition cochée est remplie."
L["Auto-hide all bars while"] = "Masquer automatiquement toutes les barres"
L["In Vehicle"] = "En véhicule"
L["Pet Battle"] = "En combat de mascottes"
L["Blizzard frames"] = "Interface Blizzard"
L["Hide Blizzard Resource Bars"] = "Masquer les barres de ressources Blizzard"
L["Hide Blizzard's detached resource bars."] = "Masque les barres de ressources détachées de Blizzard."

-- Visibility condition sections
L["Combat & Target"] = "Combat et cible"
L["PvP"] = "JcJ"
L["Mount"] = "Monture"
L["Druid Forms"] = "Formes de druide"

-- Visibility conditions
L["In Combat"] = "En combat"
L["Has Target"] = "Cible sélectionnée"
L["Hostile Target"] = "Cible hostile"
L["Attackable Target"] = "Cible attaquable"
L["Friendly Target"] = "Cible amicale"
L["Group"] = "Groupe"
L["Instance"] = "Instance"
L["In Any Group"] = "Dans un groupe"
L["In Raid Group"] = "Dans un groupe de raid"
L["In Instance"] = "En instance"
L["In Dungeon"] = "En donjon"
L["In Raid"] = "En raid"
L["In Battleground"] = "En champ de bataille"
L["In Arena"] = "En arène"
L["PvP Flagged"] = "JcJ activé"
L["War Mode"] = "Mode Guerre"
L["Mounted"] = "Monté"
L["Flying"] = "En vol"
L["Cat Form"] = "Forme de félin"
L["Bear Form"] = "Forme d'ours"
L["Moonkin Form"] = "Forme de sélénien"
L["Travel Form (Stag)"] = "Forme de voyage (cerf)"
L["Aquatic Form"] = "Forme aquatique"
L["Flight Form"] = "Forme de vol"
L["Swift Flight Form"] = "Forme de vol épique"
L["Travel Form (Any)"] = "Forme de voyage (toutes)"
L["Humanoid Form"] = "Forme humanoïde"
