local L = LibStub("AceLocale-3.0"):NewLocale("ChonkyBirb", "koKR", false)
if not L then return end

-- Resource names
L["Health"] = "생명력"
L["Mana"] = "마나"
L["Rage"] = "분노"
L["Energy"] = "기력"
L["Focus"] = "집중"
L["Runic Power"] = "룬 마력"
L["Runes"] = "룬"
L["Astral Power"] = "천공의 힘"
L["Soul Shards"] = "영혼의 조각"
L["Soul Fragments"] = "영혼 파편"
L["Holy Power"] = "신성한 힘"
L["Chi"] = "기"
L["Insanity"] = "광기"
L["Maelstrom"] = "소용돌이"
L["Fury"] = "격노"
L["Combo Points"] = "연계 점수"
L["Arcane Charges"] = "비전 충전물"
L["Essence"] = "정수"
L["Stagger"] = "시간차"
L["Stagger Colors"] = "시간차 색상"
L["Light"] = "작은 시간차"
L["Moderate"] = "중간 시간차"
L["Heavy"] = "큰 시간차"
L["Maelstrom Weapon"] = "소용돌이치는 무기"

-- Tabs / sections
L["General"] = "일반"
L["Bars"] = "바"
L["Profiles"] = "프로필"

-- General options
L["Unlock"] = "고정 해제"
L["Lock"] = "고정"
L["Unlock bars to drag and position them; every bar is shown while unlocked."] = "바를 고정 해제하면 드래그로 위치를 옮길 수 있습니다. 고정 해제 상태에서는 모든 바가 표시됩니다."
L["Link bars"] = "바 연결"
L["Drag one bar and they all move together."] = "바 하나를 드래그하면 모든 바가 함께 움직입니다."
L["Move group"] = "그룹 이동"
L["Bars unlocked — drag or use the sliders to move them."] = "바 고정 해제됨 — 드래그하거나 슬라이더로 이동하세요."

-- Global defaults (font / border / background for all bars; per-bar settings override)
L["Default appearance (all bars)"] = "기본 외형 (모든 바)"
L["Default Font"] = "기본 글꼴"
L["Default Border"] = "기본 테두리"
L["Default Background"] = "기본 배경"
L["Reset to default"] = "기본값으로 초기화"
L["Clear this bar's border & background overrides so they follow the global defaults."] = "이 바의 테두리와 배경 개별 설정을 지우고 전역 기본값을 따르게 합니다."
L["Clear this text's font overrides so it follows the global default font."] = "이 텍스트의 글꼴 개별 설정을 지우고 전역 기본 글꼴을 따르게 합니다."
L["Strata"] = "표시 층"
L["Display layer. A bar on a higher strata fully covers a lower one (text included)."] = "표시 층입니다. 더 높은 층의 바는 낮은 층의 바를 (텍스트 포함) 완전히 가립니다."
L["Copy settings from"] = "설정 복사 원본"
L["Copy another bar's look + position onto this one. Tags, visibility and the enabled state are kept."] = "다른 바의 외형과 위치를 이 바에 복사합니다. 태그, 표시 조건, 활성화 상태는 유지됩니다."
L["Cast Prediction"] = "시전 예측"
L["Predict cast generation"] = "시전으로 생성될 자원 예측"
L["While casting, preview the resource the cast will generate as a ghost segment."] = "시전 중에 생성될 자원을 반투명 칸으로 미리 보여줍니다."
L["Prediction Color"] = "예측 색상"
L["Color and opacity of the cast-prediction ghost."] = "시전 예측 반투명 칸의 색상과 불투명도입니다."
L["Bar Color + Opacity"] = "바 색상 및 불투명도"
L["Custom Color"] = "사용자 지정 색상"
L["Opacity"] = "불투명도"

-- Value markers
L["Markers"] = "표식"
L["Marker"] = "표식"
L["Add Marker"] = "표식 추가"
L["Value"] = "값"
L["Position of the marker, in resource value."] = "표식의 위치 (자원 값 기준)."
L["Marker thickness."] = "표식 두께."
L["Bar Height"] = "바 높이"
L["Custom Height"] = "사용자 지정 높이"
L["Marker Color"] = "표식 색상"
L["Marker color and opacity."] = "표식의 색상과 불투명도입니다."
L["All spells are known"] = "모든 주문을 배웠을 때"
L["At least one spell is known"] = "주문을 하나 이상 배웠을 때"
L["No spell is known"] = "어떤 주문도 배우지 않았을 때"
L["Add Spell"] = "주문 추가"
L["Spell ID, name, or a shift-clicked talent link."] = "주문 ID, 이름, 또는 Shift+클릭한 특성 링크."
L["Marker Type"] = "표식 유형"
L["Static Value"] = "고정 값"
L["Spell Cost"] = "주문 소모량"
L["Spell"] = "주문"
L["Count"] = "개수"
L["Places markers at 1x, 2x, 3x... the spell's cost."] = "주문 소모량의 1배, 2배, 3배… 위치에 표식을 배치합니다."
L["Cost:"] = "소모량:"
L["No flat cost found for this bar's resource."] = "이 바의 자원에 대한 고정 소모량을 찾을 수 없습니다."

-- Per-bar options
L["Enabled"] = "활성화"
L["Width"] = "너비"
L["Height"] = "높이"
L["Position"] = "위치"
L["Position X"] = "X 위치"
L["Position Y"] = "Y 위치"
L["Scale"] = "크기 비율"
L["Bar Texture"] = "바 텍스처"
L["Bar Color"] = "바 색상"
L["Background Texture"] = "배경 텍스처"
L["Background Color"] = "배경 색상"
L["Border Texture"] = "테두리 텍스처"
L["Border Size"] = "테두리 크기"
L["Border Color"] = "테두리 색상"
L["Fill Direction"] = "채우기 방향"
L["Segment Spacing"] = "칸 간격"
L["Gap between segments, in pixels."] = "칸 사이의 간격 (픽셀)."
L["Inactive Segments"] = "비활성 칸"
L["Inactive Segment Color"] = "비활성 칸 색상"
L["Color + Opacity"] = "색상 및 불투명도"
L["Recharge Display"] = "재충전 표시"
L["Recharge Color"] = "재충전 색상"

-- Color by percent
L["Color Mode"] = "색상 모드"
L["Static"] = "고정"
L["By Percent"] = "백분율 기준"
L["The bar recolors based on its fill percentage."] = "채워진 비율에 따라 바 색상이 바뀝니다."
L["Color by percent"] = "백분율별 색상"
L["Curve Type"] = "곡선 유형"
L["Sharp Steps"] = "단계별 변화"
L["Smooth Gradient"] = "부드러운 그라데이션"
L["Add Color"] = "색상 추가"
L["Color"] = "색상"
L["Font"] = "글꼴"
L["Font Size"] = "글꼴 크기"
L["Outline"] = "외곽선"
L["Font Color"] = "글꼴 색상"

-- Fill directions
L["Left to Right"] = "왼쪽에서 오른쪽"
L["Right to Left"] = "오른쪽에서 왼쪽"
L["Bottom to Top"] = "아래에서 위"
L["Top to Bottom"] = "위에서 아래"

-- Font outline / shadow
L["None"] = "없음"
L["Thick Outline"] = "굵은 외곽선"
L["Shadow"] = "그림자"
L["Shadow Color"] = "그림자 색상"
L["Shadow X"] = "그림자 X"
L["Shadow Y"] = "그림자 Y"

-- Text fields
L["Text"] = "텍스트"
L["Texts"] = "텍스트 목록"
L["Add Text"] = "텍스트 추가"
L["Remove"] = "제거"
L["Anchor"] = "기준점"
L["X"] = "X"
L["Y"] = "Y"
L["Tags"] = "태그"

-- Text tags: bar-relative, name + mouseover description
L["Current Value"] = "현재 값"
L["Max Value"] = "최대 값"
L["Current / Max"] = "현재 / 최대"
L["Percent"] = "백분율"
L["Deficit"] = "부족량"
L["Current (full)"] = "현재 (전체 숫자)"
L["Max (full)"] = "최대 (전체 숫자)"
L["Current / Max (full)"] = "현재 / 최대 (전체 숫자)"
L["Resource Name"] = "자원 이름"
L["Current value of this bar's resource (short form)."] = "이 바 자원의 현재 값 (축약형)."
L["Maximum value of this bar's resource (short form)."] = "이 바 자원의 최대 값 (축약형)."
L["Current and maximum, shown as cur/max (short form)."] = "현재 값과 최대 값을 현재/최대 형식으로 표시 (축약형)."
L["Current value as a percentage (0-100%)."] = "현재 값을 백분율로 표시 (0-100%)."
L["Missing amount (max minus current)."] = "부족한 양 (최대 값에서 현재 값을 뺀 값)."
L["Current value, full number (not abbreviated)."] = "현재 값, 전체 숫자 (축약 없음)."
L["Maximum value, full number (not abbreviated)."] = "최대 값, 전체 숫자 (축약 없음)."
L["Current and maximum as cur/max, full numbers."] = "현재 값과 최대 값을 현재/최대 형식으로 표시, 전체 숫자."
L["Name of the resource (e.g. Energy)."] = "자원의 이름 (예: 기력)."

-- Text tags: absolute class resources
L["Current number of combo points."] = "현재 연계 점수."
L["Current number of soul shards."] = "현재 영혼의 조각 개수."
L["Current holy power."] = "현재 신성한 힘."
L["Current number of Chi."] = "현재 기 개수."
L["Current number of arcane charges."] = "현재 비전 충전물 개수."
L["Current number of ready runes."] = "현재 사용 가능한 룬 개수."
L["Current runic power."] = "현재 룬 마력."
L["Current number of essence."] = "현재 정수."
L["Current insanity."] = "현재 광기."
L["Current maelstrom."] = "현재 소용돌이."
L["Current astral power."] = "현재 천공의 힘."
L["Current fury."] = "현재 격노."
L["Current mana."] = "현재 마나."

-- Visibility
L["Visibility"] = "표시 조건"
L["Show"] = "표시"
L["Always"] = "항상"
L["Automatic"] = "자동"
L["Never"] = "표시 안 함"
L["Custom"] = "사용자 지정"
L["Automatic shows the bar only while its resource is relevant (forms, spec)."] = "자동은 해당 자원이 유효할 때만 (변신, 전문화) 바를 표시합니다."
L["The bar shows when any checked condition is true."] = "선택한 조건 중 하나라도 충족되면 바가 표시됩니다."
L["Auto-hide all bars while"] = "다음 상황에서 모든 바 자동 숨김"
L["In Vehicle"] = "차량 탑승 중"
L["Pet Battle"] = "애완동물 대전 중"
L["Blizzard frames"] = "블리자드 기본 창"
L["Hide Blizzard Resource Bars"] = "블리자드 자원 바 숨기기"
L["Hide Blizzard's detached resource bars."] = "블리자드의 분리된 자원 바를 숨깁니다."

-- Visibility condition sections
L["Combat & Target"] = "전투 및 대상"
L["PvP"] = "PvP"
L["Mount"] = "탈것"
L["Druid Forms"] = "드루이드 변신"

-- Visibility conditions
L["In Combat"] = "전투 중"
L["Has Target"] = "대상 있음"
L["Hostile Target"] = "적대적 대상"
L["Attackable Target"] = "공격 가능한 대상"
L["Friendly Target"] = "우호적 대상"
L["Group"] = "파티"
L["Instance"] = "인스턴스"
L["In Any Group"] = "파티 또는 공격대 소속"
L["In Raid Group"] = "공격대 소속"
L["In Instance"] = "인스턴스 안"
L["In Dungeon"] = "던전 안"
L["In Raid"] = "공격대 던전 안"
L["In Battleground"] = "전장 안"
L["In Arena"] = "투기장 안"
L["PvP Flagged"] = "PvP 활성화"
L["War Mode"] = "전쟁 모드"
L["Mounted"] = "탈것 탑승 중"
L["Flying"] = "비행 중"
L["Cat Form"] = "표범 변신"
L["Bear Form"] = "곰 변신"
L["Moonkin Form"] = "달빛야수 변신"
L["Travel Form (Stag)"] = "날쌘 동물 변신 (수사슴)"
L["Aquatic Form"] = "수중 동물 변신"
L["Flight Form"] = "폭풍날개 변신"
L["Swift Flight Form"] = "폭풍날개 변신 (영웅)"
L["Travel Form (Any)"] = "날쌘 동물 변신 (모두)"
L["Humanoid Form"] = "인간형"
