local L = LibStub("AceLocale-3.0"):NewLocale("ChonkyBirb", "ruRU", false)
if not L then return end

-- Resource names
L["Health"] = "Здоровье"
L["Mana"] = "Мана"
L["Rage"] = "Ярость"
L["Energy"] = "Энергия"
L["Focus"] = "Концентрация"
L["Runic Power"] = "Сила рун"
L["Runes"] = "Руны"
L["Astral Power"] = "Астральная мощь"
L["Soul Shards"] = "Осколки души"
L["Soul Fragments"] = "Фрагменты души"
L["Holy Power"] = "Энергия Света"
L["Chi"] = "Энергия ци"
L["Insanity"] = "Безумие"
L["Maelstrom"] = "Энергия Водоворота"
L["Fury"] = "Гнев"
L["Combo Points"] = "Длина серии приемов"
L["Arcane Charges"] = "Чародейские заряды"
L["Essence"] = "Сущность"
L["Stagger"] = "Пошатывание"
L["Stagger Colors"] = "Цвета пошатывания"
L["Light"] = "Легкое"
L["Moderate"] = "Умеренное"
L["Heavy"] = "Сильное"
L["Maelstrom Weapon"] = "Оружие Водоворота"

-- Tabs / sections
L["General"] = "Общее"
L["Bars"] = "Полосы"
L["Profiles"] = "Профили"

-- General options
L["Unlock"] = "Открепить"
L["Lock"] = "Закрепить"
L["Unlock bars to drag and position them; every bar is shown while unlocked."] = "Открепите полосы, чтобы перетаскивать и размещать их; пока они откреплены, показаны все полосы."
L["Link bars"] = "Связать полосы"
L["Drag one bar and they all move together."] = "Перетащите одну полосу, и все сдвинутся вместе."
L["Move group"] = "Переместить группу"
L["Bars unlocked — drag or use the sliders to move them."] = "Полосы откреплены — перетащите их или используйте ползунки."

-- Global defaults (font / border / background for all bars; per-bar settings override)
L["Default appearance (all bars)"] = "Внешний вид по умолчанию (все полосы)"
L["Default Font"] = "Шрифт по умолчанию"
L["Default Border"] = "Окантовка по умолчанию"
L["Default Background"] = "Фон по умолчанию"
L["Reset to default"] = "Сбросить к значению по умолчанию"
L["Clear this bar's border & background overrides so they follow the global defaults."] = "Сбрасывает собственные настройки окантовки и фона этой полосы, чтобы она следовала общим значениям."
L["Clear this text's font overrides so it follows the global default font."] = "Сбрасывает собственный шрифт этого текста, чтобы он следовал общему шрифту."
L["Strata"] = "Слой"
L["Display layer. A bar on a higher strata fully covers a lower one (text included)."] = "Слой отображения. Полоса на более высоком слое полностью перекрывает нижнюю (включая текст)."
L["Copy settings from"] = "Копировать настройки из"
L["Copy another bar's look + position onto this one. Tags, visibility and the enabled state are kept."] = "Копирует внешний вид и положение другой полосы на эту. Теги, отображение и состояние включения сохраняются."
L["Cast Prediction"] = "Прогноз заклинания"
L["Predict cast generation"] = "Прогнозировать получаемый ресурс"
L["While casting, preview the resource the cast will generate as a ghost segment."] = "Во время применения заклинания показывает получаемый ресурс призрачным сегментом."
L["Prediction Color"] = "Цвет прогноза"
L["Color and opacity of the cast-prediction ghost."] = "Цвет и непрозрачность призрачного сегмента прогноза."
L["Bar Color + Opacity"] = "Цвет и непрозрачность полосы"
L["Custom Color"] = "Свой цвет"
L["Opacity"] = "Непрозрачность"

-- Value markers
L["Markers"] = "Отметки"
L["Marker"] = "Отметка"
L["Add Marker"] = "Добавить отметку"
L["Value"] = "Значение"
L["Position of the marker, in resource value."] = "Положение отметки в единицах ресурса."
L["Marker thickness."] = "Толщина отметки."
L["Bar Height"] = "Высота полосы"
L["Custom Height"] = "Своя высота"
L["Marker Color"] = "Цвет отметки"
L["Marker color and opacity."] = "Цвет и непрозрачность отметки."
L["All spells are known"] = "Известны все заклинания"
L["At least one spell is known"] = "Известно хотя бы одно заклинание"
L["No spell is known"] = "Ни одно заклинание не известно"
L["Add Spell"] = "Добавить заклинание"
L["Spell ID, name, or a shift-clicked talent link."] = "ID заклинания, название или ссылка на талант, вставленная через Shift+клик."
L["Marker Type"] = "Тип отметки"
L["Static Value"] = "Фиксированное значение"
L["Spell Cost"] = "Стоимость заклинания"
L["Spell"] = "Заклинание"
L["Count"] = "Количество"
L["Places markers at 1x, 2x, 3x... the spell's cost."] = "Ставит отметки на 1x, 2x, 3x… стоимости заклинания."
L["Cost:"] = "Стоимость:"
L["No flat cost found for this bar's resource."] = "Фиксированная стоимость для ресурса этой полосы не найдена."

-- Per-bar options
L["Enabled"] = "Включена"
L["Width"] = "Ширина"
L["Height"] = "Высота"
L["Position"] = "Позиция"
L["Position X"] = "Позиция X"
L["Position Y"] = "Позиция Y"
L["Scale"] = "Масштаб"
L["Bar Texture"] = "Текстура полосы"
L["Bar Color"] = "Цвет полосы"
L["Background Texture"] = "Текстура фона"
L["Background Color"] = "Цвет фона"
L["Border Texture"] = "Текстура окантовки"
L["Border Size"] = "Размер окантовки"
L["Border Color"] = "Цвет окантовки"
L["Fill Direction"] = "Направление заполнения"
L["Segment Spacing"] = "Отступ между сегментами"
L["Gap between segments, in pixels."] = "Промежуток между сегментами в пикселях."
L["Inactive Segments"] = "Неактивные сегменты"
L["Inactive Segment Color"] = "Цвет неактивных сегментов"
L["Color + Opacity"] = "Цвет и непрозрачность"
L["Recharge Display"] = "Отображение восстановления"
L["Recharge Color"] = "Цвет восстановления"

-- Color by percent
L["Color Mode"] = "Режим цвета"
L["Static"] = "Статический"
L["By Percent"] = "По проценту"
L["The bar recolors based on its fill percentage."] = "Полоса меняет цвет в зависимости от процента заполнения."
L["Color by percent"] = "Цвет по проценту"
L["Curve Type"] = "Тип кривой"
L["Sharp Steps"] = "Резкие ступени"
L["Smooth Gradient"] = "Плавный градиент"
L["Add Color"] = "Добавить цвет"
L["Color"] = "Цвет"
L["Font"] = "Шрифт"
L["Font Size"] = "Размер шрифта"
L["Outline"] = "Контур"
L["Font Color"] = "Цвет шрифта"

-- Fill directions
L["Left to Right"] = "Слева направо"
L["Right to Left"] = "Справа налево"
L["Bottom to Top"] = "Снизу вверх"
L["Top to Bottom"] = "Сверху вниз"

-- Font outline / shadow
L["None"] = "Нет"
L["Thick Outline"] = "Толстый контур"
L["Shadow"] = "Тень"
L["Shadow Color"] = "Цвет тени"
L["Shadow X"] = "Тень X"
L["Shadow Y"] = "Тень Y"

-- Text fields
L["Text"] = "Текст"
L["Texts"] = "Тексты"
L["Add Text"] = "Добавить текст"
L["Remove"] = "Удалить"
L["Anchor"] = "Привязка"
L["X"] = "X"
L["Y"] = "Y"
L["Tags"] = "Теги"

-- Text tags: bar-relative, name + mouseover description
L["Current Value"] = "Текущее значение"
L["Max Value"] = "Максимальное значение"
L["Current / Max"] = "Текущее / Макс."
L["Percent"] = "Процент"
L["Deficit"] = "Нехватка"
L["Current (full)"] = "Текущее (полностью)"
L["Max (full)"] = "Макс. (полностью)"
L["Current / Max (full)"] = "Текущее / Макс. (полностью)"
L["Resource Name"] = "Название ресурса"
L["Current value of this bar's resource (short form)."] = "Текущее значение ресурса этой полосы (сокращенно)."
L["Maximum value of this bar's resource (short form)."] = "Максимальное значение ресурса этой полосы (сокращенно)."
L["Current and maximum, shown as cur/max (short form)."] = "Текущее и максимальное значение в виде тек/макс (сокращенно)."
L["Current value as a percentage (0-100%)."] = "Текущее значение в процентах (0-100%)."
L["Missing amount (max minus current)."] = "Недостающее количество (максимум минус текущее)."
L["Current value, full number (not abbreviated)."] = "Текущее значение, полное число (без сокращения)."
L["Maximum value, full number (not abbreviated)."] = "Максимальное значение, полное число (без сокращения)."
L["Current and maximum as cur/max, full numbers."] = "Текущее и максимальное значение в виде тек/макс, полные числа."
L["Name of the resource (e.g. Energy)."] = "Название ресурса (например, Энергия)."

-- Text tags: absolute class resources
L["Current number of combo points."] = "Текущая длина серии приемов."
L["Current number of soul shards."] = "Текущее число осколков души."
L["Current holy power."] = "Текущая энергия Света."
L["Current number of Chi."] = "Текущая энергия ци."
L["Current number of arcane charges."] = "Текущее число чародейских зарядов."
L["Current number of ready runes."] = "Текущее число готовых рун."
L["Current runic power."] = "Текущая сила рун."
L["Current number of essence."] = "Текущая сущность."
L["Current insanity."] = "Текущее безумие."
L["Current maelstrom."] = "Текущая энергия Водоворота."
L["Current astral power."] = "Текущая астральная мощь."
L["Current fury."] = "Текущий гнев."
L["Current mana."] = "Текущая мана."

-- Visibility
L["Visibility"] = "Отображение"
L["Show"] = "Показывать"
L["Always"] = "Всегда"
L["Automatic"] = "Автоматически"
L["Never"] = "Никогда"
L["Custom"] = "Свои условия"
L["Automatic shows the bar only while its resource is relevant (forms, spec)."] = "«Автоматически» показывает полосу, только пока ее ресурс актуален (облик, специализация)."
L["The bar shows when any checked condition is true."] = "Полоса показывается, когда выполняется любое из отмеченных условий."
L["Auto-hide all bars while"] = "Автоматически скрывать все полосы"
L["In Vehicle"] = "В транспорте"
L["Pet Battle"] = "В битве питомцев"
L["Blizzard frames"] = "Элементы Blizzard"
L["Hide Blizzard Resource Bars"] = "Скрыть полосы ресурсов Blizzard"
L["Hide Blizzard's detached resource bars."] = "Скрывает отдельные полосы ресурсов Blizzard."

-- Visibility condition sections
L["Combat & Target"] = "Бой и цель"
L["PvP"] = "PvP"
L["Mount"] = "Транспорт"
L["Druid Forms"] = "Облики друида"

-- Visibility conditions
L["In Combat"] = "В бою"
L["Has Target"] = "Есть цель"
L["Hostile Target"] = "Враждебная цель"
L["Attackable Target"] = "Атакуемая цель"
L["Friendly Target"] = "Дружественная цель"
L["Group"] = "Группа"
L["Instance"] = "Инстансы"
L["In Any Group"] = "В любой группе"
L["In Raid Group"] = "В рейдовой группе"
L["In Instance"] = "В инстансе"
L["In Dungeon"] = "В подземелье"
L["In Raid"] = "В рейде"
L["In Battleground"] = "На поле боя"
L["In Arena"] = "На арене"
L["PvP Flagged"] = "PvP-режим включен"
L["War Mode"] = "Режим войны"
L["Mounted"] = "Верхом"
L["Flying"] = "В полете"
L["Cat Form"] = "Облик кошки"
L["Bear Form"] = "Облик медведя"
L["Moonkin Form"] = "Облик лунного совуха"
L["Travel Form (Stag)"] = "Походный облик (олень)"
L["Aquatic Form"] = "Водный облик"
L["Flight Form"] = "Облик птицы"
L["Swift Flight Form"] = "Облик стремительной птицы"
L["Travel Form (Any)"] = "Походный облик (любой)"
L["Humanoid Form"] = "Облик гуманоида"
