local L = LibStub("AceLocale-3.0"):NewLocale("ChonkyBirb", "zhCN", false)
if not L then return end

-- 资源名称
L["Health"] = "生命值"
L["Mana"] = "法力值"
L["Rage"] = "怒气"
L["Energy"] = "能量"
L["Focus"] = "集中值"
L["Runic Power"] = "符文能量"
L["Runes"] = "符文"
L["Astral Power"] = "星界能量"
L["Soul Shards"] = "灵魂碎片"
L["Soul Fragments"] = "灵魂残片"
L["Holy Power"] = "神圣能量"
L["Chi"] = "真气"
L["Insanity"] = "狂乱值"
L["Maelstrom"] = "漩涡值"
L["Fury"] = "恶魔之怒"
L["Combo Points"] = "连击点"
L["Arcane Charges"] = "奥术充能"
L["Essence"] = "精华"
L["Stagger"] = "醉拳值"
L["Stagger Colors"] = "醉拳颜色"
L["Light"] = "轻度"
L["Moderate"] = "中度"
L["Heavy"] = "重度"
L["Maelstrom Weapon"] = "漩涡武器"

-- 标签页 / 分类
L["General"] = "通用"
L["Bars"] = "条体"
L["Profiles"] = "配置文件"

-- 通用选项
L["Unlock"] = "解锁"
L["Lock"] = "锁定"
L["Unlock bars to drag and position them; every bar is shown while unlocked."] = "解锁条体后可拖拽调整位置；解锁状态下所有条体都会显示。"
L["Link bars"] = "联动条体"
L["Drag one bar and they all move together."] = "拖拽任意一条，所有条体会同步移动。"
L["Move group"] = "移动整组"
L["Bars unlocked — drag or use the sliders to move them."] = "条体已解锁 — 拖拽或拖动滑块来移动。"

-- 全局默认（全部条体共用的字体/边框/背景；单条设置会覆盖全局）
L["Default appearance (all bars)"] = "默认外观（全部条体）"
L["Default Font"] = "默认字体"
L["Default Border"] = "默认边框"
L["Default Background"] = "默认背景"
L["Reset to default"] = "恢复默认"
L["Clear this bar's border & background overrides so they follow the global defaults."] = "清除此条体自定义的边框与背景，恢复跟随全局默认设置。"
L["Clear this text's font overrides so it follows the global default font."] = "清除该文本自定义字体，恢复跟随全局默认字体。"
L["Strata"] = "显示层级"
L["Display layer. A bar on a higher strata fully covers a lower one (text included)."] = "显示层级。高层级条体会完全遮挡低层级条体（包含文字）。"
L["Copy settings from"] = "复制设置自"
L["Copy another bar's look + position onto this one. Tags, visibility and the enabled state are kept."] = "将其他条体的外观与位置复制到此条。标签、显示条件与启用状态保持不变。"
L["Cast Prediction"] = "施法预演"
L["Predict cast generation"] = "预演施法产生资源"
L["While casting, preview the resource the cast will generate as a ghost segment."] = "施法过程中，以半透明片段预览该法术完成后获得的资源。"
L["Prediction Color"] = "预演颜色"
L["Color and opacity of the cast-prediction ghost."] = "施法预演半透明片段的颜色与透明度。"
L["Bar Color + Opacity"] = "条体颜色与透明度"
L["Custom Color"] = "自定义颜色"
L["Opacity"] = "透明度"

-- 数值标记
L["Markers"] = "标记"
L["Marker"] = "标记"
L["Add Marker"] = "添加标记"
L["Value"] = "数值"
L["Position of the marker, in resource value."] = "标记所在位置，以资源数值为单位。"
L["Marker thickness."] = "标记线条粗细。"
L["Bar Height"] = "条体高度"
L["Custom Height"] = "自定义高度"
L["Marker Color"] = "标记颜色"
L["Marker color and opacity."] = "标记的颜色与透明度。"
L["All spells are known"] = "已学会全部法术"
L["At least one spell is known"] = "至少学会一个法术"
L["No spell is known"] = "未学会该法术"
L["Add Spell"] = "添加法术"
L["Spell ID, name, or a shift-clicked talent link."] = "法术ID、法术名称，或者Shift点击天赋链接填入。"
L["Marker Type"] = "标记类型"
L["Static Value"] = "固定数值"
L["Spell Cost"] = "法术消耗"
L["Spell"] = "法术"
L["Count"] = "计数"
L["Places markers at 1x, 2x, 3x... the spell's cost."] = "按照法术消耗的1倍、2倍、3倍……位置生成标记。"
L["Cost:"] = "消耗："
L["No flat cost found for this bar's resource."] = "未找到该资源对应的固定消耗数值。"

-- 单条体选项
L["Enabled"] = "启用"
L["Width"] = "宽度"
L["Height"] = "高度"
L["Position"] = "位置"
L["Position X"] = "X坐标"
L["Position Y"] = "Y坐标"
L["Scale"] = "缩放"
L["Bar Texture"] = "条体贴图"
L["Bar Color"] = "条体颜色"
L["Background Texture"] = "背景贴图"
L["Background Color"] = "背景颜色"
L["Border Texture"] = "边框贴图"
L["Border Size"] = "边框尺寸"
L["Border Color"] = "边框颜色"
L["Fill Direction"] = "填充方向"
L["Segment Spacing"] = "分段间距"
L["Gap between segments, in pixels."] = "各个分段之间的像素间距。"
L["Inactive Segments"] = "未激活分段"
L["Inactive Segment Color"] = "未激活分段颜色"
L["Color + Opacity"] = "颜色与透明度"
L["Recharge Display"] = "充能显示"
L["Recharge Color"] = "充能颜色"

-- 按百分比变色
L["Color Mode"] = "颜色模式"
L["Static"] = "固定颜色"
L["By Percent"] = "按百分比"
L["The bar recolors based on its fill percentage."] = "条体颜色会根据填充百分比动态变化。"
L["Color by percent"] = "按百分比变色"
L["Curve Type"] = "过渡类型"
L["Sharp Steps"] = "阶跃突变"
L["Smooth Gradient"] = "平滑渐变"
L["Add Color"] = "添加颜色节点"
L["Color"] = "颜色"
L["Font"] = "字体"
L["Font Size"] = "字号"
L["Outline"] = "描边"
L["Font Color"] = "字体颜色"

-- 填充方向
L["Left to Right"] = "从左到右"
L["Right to Left"] = "从右到左"
L["Bottom to Top"] = "从下到上"
L["Top to Bottom"] = "从上到下"

-- 字体描边 / 阴影
L["None"] = "无"
L["Outline"] = "细描边"
L["Thick Outline"] = "粗描边"
L["Shadow"] = "阴影"
L["Shadow Color"] = "阴影颜色"
L["Shadow X"] = "阴影X偏移"
L["Shadow Y"] = "阴影Y偏移"

-- 文本字段
L["Text"] = "文本"
L["Texts"] = "文本列表"
L["Add Text"] = "添加文本"
L["Remove"] = "移除"
L["Anchor"] = "锚点"
L["X"] = "X"
L["Y"] = "Y"
L["Tags"] = "标签"

-- 文本标签：条体相关、名称与鼠标悬浮说明
L["Current Value"] = "当前数值"
L["Max Value"] = "最大数值"
L["Current / Max"] = "当前/最大"
L["Percent"] = "百分比"
L["Deficit"] = "缺口值"
L["Current (full)"] = "当前（完整数字）"
L["Max (full)"] = "最大值（完整数字）"
L["Current / Max (full)"] = "当前 / 最大（完整数字）"
L["Resource Name"] = "资源名称"
L["Current value of this bar's resource (short form)."] = "该条体资源的当前数值（简写）。"
L["Maximum value of this bar's resource (short form)."] = "该条体资源的最大数值（简写）。"
L["Current and maximum, shown as cur/max (short form)."] = "显示当前/最大值（简写）。"
L["Current value as a percentage (0-100%)."] = "以百分比显示当前数值（0-100%）。"
L["Missing amount (max minus current)."] = "缺失数值（最大值减去当前值）。"
L["Current value, full number (not abbreviated)."] = "当前数值，完整数字，不缩写。"
L["Maximum value, full number (not abbreviated)."] = "最大数值，完整数字，不缩写。"
L["Current and maximum as cur/max, full numbers."] = "当前/最大值，使用完整数字。"
L["Name of the resource (e.g. Energy)."] = "资源的名称（例如：能量）。"

-- 文本标签：职业专属资源
L["Current number of combo points."] = "当前连击点数量。"
L["Current number of soul shards."] = "当前灵魂碎片数量。"
L["Current holy power."] = "当前神圣能量数值。"
L["Current number of Chi."] = "当前真气数量。"
L["Current number of arcane charges."] = "当前奥术充能层数。"
L["Current number of ready runes."] = "已就绪符文数量。"
L["Current runic power."] = "当前符文能量。"
L["Current number of essence."] = "当前精华数量。"
L["Current insanity."] = "当前狂乱值。"
L["Current maelstrom."] = "当前漩涡值。"
L["Current astral power."] = "当前星界能量。"
L["Current fury."] = "当前恶魔之怒。"
L["Current mana."] = "当前法力值。"

-- 显示控制
L["Visibility"] = "显示条件"
L["Show"] = "显示"
L["Always"] = "始终显示"
L["Automatic"] = "自动"
L["Never"] = "永不显示"
L["Custom"] = "自定义"
L["Automatic shows the bar only while its resource is relevant (forms, spec)."] = "自动模式：仅在该资源生效时显示（对应形态、专精）。"
L["The bar shows when any checked condition is true."] = "勾选任意条件满足时，条体就会显示。"
L["Auto-hide all bars while"] = "当以下情况时自动隐藏全部条体"
L["In Vehicle"] = "载具内"
L["Pet Battle"] = "宠物对战"
L["Blizzard frames"] = "暴雪原生框体"
L["Hide Blizzard Resource Bars"] = "隐藏暴雪原生资源条"
L["Hide Blizzard's detached resource bars."] = "隐藏暴雪分离出来的职业资源条。"

-- 显示条件分组
L["Combat & Target"] = "战斗与目标"
L["PvP"] = "PVP"
L["Mount"] = "坐骑"
L["Druid Forms"] = "德鲁伊形态"

-- 显示条件项
L["In Combat"] = "战斗中"
L["Has Target"] = "拥有目标"
L["Hostile Target"] = "敌对目标"
L["Attackable Target"] = "可攻击目标"
L["Friendly Target"] = "友方目标"
L["Group"] = "队伍"
L["Instance"] = "副本"
L["In Any Group"] = "任意队伍中"
L["In Raid Group"] = "团队队伍中"
L["In Instance"] = "副本内"
L["In Dungeon"] = "地下城"
L["In Raid"] = "团队副本"
L["In Battleground"] = "战场"
L["In Arena"] = "竞技场"
L["PvP Flagged"] = "开启PVP标记"
L["War Mode"] = "战争模式"
L["Mounted"] = "骑乘状态"
L["Flying"] = "飞行中"
L["Cat Form"] = "猎豹形态"
L["Bear Form"] = "熊形态"
L["Moonkin Form"] = "枭兽形态"
L["Travel Form (Stag)"] = "旅行形态（雄鹿）"
L["Aquatic Form"] = "水栖形态"
L["Flight Form"] = "飞行形态"
L["Swift Flight Form"] = "迅捷飞行形态"
L["Travel Form (Any)"] = "任意旅行形态"
L["Humanoid Form"] = "人形态"
