local L = LibStub("AceLocale-3.0"):NewLocale("ChonkyBirb", "zhTW", false)
if not L then return end

-- Resource names
L["Health"] = "生命力"
L["Mana"] = "法力"
L["Rage"] = "怒氣"
L["Energy"] = "能量"
L["Focus"] = "專注"
L["Runic Power"] = "符能"
L["Runes"] = "符文"
L["Astral Power"] = "星能"
L["Soul Shards"] = "靈魂裂片"
L["Soul Fragments"] = "靈魂碎片"
L["Holy Power"] = "聖能"
L["Chi"] = "真氣"
L["Insanity"] = "瘋狂"
L["Maelstrom"] = "元能"
L["Fury"] = "魔怒"
L["Combo Points"] = "連擊點數"
L["Arcane Charges"] = "秘法充能"
L["Essence"] = "龍能"
L["Stagger"] = "醉仙緩勁"
L["Stagger Colors"] = "醉仙緩勁顏色"
L["Light"] = "醉仙小緩勁"
L["Moderate"] = "醉仙中緩勁"
L["Heavy"] = "醉仙大緩勁"
L["Maelstrom Weapon"] = "氣漩武器"

-- Tabs / sections
L["General"] = "一般"
L["Bars"] = "計量條"
L["Profiles"] = "設定檔"

-- General options
L["Unlock"] = "解鎖"
L["Lock"] = "鎖定"
L["Unlock bars to drag and position them; every bar is shown while unlocked."] = "解鎖計量條後可拖曳調整位置；解鎖期間所有計量條都會顯示。"
L["Link bars"] = "連動計量條"
L["Drag one bar and they all move together."] = "拖曳任一計量條，全部會一起移動。"
L["Move group"] = "移動整組"
L["Bars unlocked — drag or use the sliders to move them."] = "計量條已解鎖 — 拖曳或使用滑桿來移動。"

-- Global defaults (font / border / background for all bars; per-bar settings override)
L["Default appearance (all bars)"] = "預設外觀（所有計量條）"
L["Default Font"] = "預設字型"
L["Default Border"] = "預設邊框"
L["Default Background"] = "預設背景"
L["Reset to default"] = "恢復預設"
L["Clear this bar's border & background overrides so they follow the global defaults."] = "清除此計量條自訂的邊框與背景，改為跟隨全域預設。"
L["Clear this text's font overrides so it follows the global default font."] = "清除此文字自訂的字型，改為跟隨全域預設字型。"
L["Strata"] = "框架層級"
L["Display layer. A bar on a higher strata fully covers a lower one (text included)."] = "顯示層級。較高層級的計量條會完全遮蓋較低層級者（包含文字）。"
L["Copy settings from"] = "複製設定來源"
L["Copy another bar's look + position onto this one. Tags, visibility and the enabled state are kept."] = "將另一個計量條的外觀與位置複製到此條。標籤、顯示條件與啟用狀態維持不變。"
L["Cast Prediction"] = "施法預測"
L["Predict cast generation"] = "預測施法產生的資源"
L["While casting, preview the resource the cast will generate as a ghost segment."] = "施法期間，以半透明區段預覽該法術將產生的資源。"
L["Prediction Color"] = "預測顏色"
L["Color and opacity of the cast-prediction ghost."] = "施法預測半透明區段的顏色與不透明度。"
L["Bar Color + Opacity"] = "計量條顏色與不透明度"
L["Custom Color"] = "自訂顏色"
L["Opacity"] = "不透明度"

-- Value markers
L["Markers"] = "標記"
L["Marker"] = "標記"
L["Add Marker"] = "新增標記"
L["Value"] = "數值"
L["Position of the marker, in resource value."] = "標記的位置，以資源數值為單位。"
L["Marker thickness."] = "標記粗細。"
L["Bar Height"] = "計量條高度"
L["Custom Height"] = "自訂高度"
L["Marker Color"] = "標記顏色"
L["Marker color and opacity."] = "標記的顏色與不透明度。"
L["All spells are known"] = "已學會所有法術"
L["At least one spell is known"] = "至少學會一個法術"
L["No spell is known"] = "未學會任何法術"
L["Add Spell"] = "新增法術"
L["Spell ID, name, or a shift-clicked talent link."] = "法術 ID、名稱，或以 Shift 點擊插入的天賦連結。"
L["Marker Type"] = "標記類型"
L["Static Value"] = "固定數值"
L["Spell Cost"] = "法術消耗"
L["Spell"] = "法術"
L["Count"] = "數量"
L["Places markers at 1x, 2x, 3x... the spell's cost."] = "在法術消耗的 1 倍、2 倍、3 倍……位置放置標記。"
L["Cost:"] = "消耗："
L["No flat cost found for this bar's resource."] = "找不到此計量條資源的固定消耗。"

-- Per-bar options
L["Enabled"] = "啟用"
L["Width"] = "寬度"
L["Height"] = "高度"
L["Position"] = "位置"
L["Position X"] = "X 位置"
L["Position Y"] = "Y 位置"
L["Scale"] = "比例"
L["Bar Texture"] = "計量條材質"
L["Bar Color"] = "計量條顏色"
L["Background Texture"] = "背景材質"
L["Background Color"] = "背景顏色"
L["Border Texture"] = "邊框材質"
L["Border Size"] = "邊框大小"
L["Border Color"] = "邊框顏色"
L["Fill Direction"] = "填充方向"
L["Segment Spacing"] = "區段間距"
L["Gap between segments, in pixels."] = "區段之間的間距（像素）。"
L["Inactive Segments"] = "未啟用區段"
L["Inactive Segment Color"] = "未啟用區段顏色"
L["Color + Opacity"] = "顏色與不透明度"
L["Recharge Display"] = "充能顯示"
L["Recharge Color"] = "充能顏色"

-- Color by percent
L["Color Mode"] = "顏色模式"
L["Static"] = "固定"
L["By Percent"] = "依百分比"
L["The bar recolors based on its fill percentage."] = "計量條會依填充百分比改變顏色。"
L["Color by percent"] = "依百分比變色"
L["Curve Type"] = "曲線類型"
L["Sharp Steps"] = "階梯式"
L["Smooth Gradient"] = "平滑漸層"
L["Add Color"] = "新增顏色"
L["Color"] = "顏色"
L["Font"] = "字型"
L["Font Size"] = "字型大小"
L["Outline"] = "外框"
L["Font Color"] = "字型顏色"

-- Fill directions
L["Left to Right"] = "由左至右"
L["Right to Left"] = "由右至左"
L["Bottom to Top"] = "由下至上"
L["Top to Bottom"] = "由上至下"

-- Font outline / shadow
L["None"] = "無"
L["Thick Outline"] = "粗外框"
L["Shadow"] = "陰影"
L["Shadow Color"] = "陰影顏色"
L["Shadow X"] = "陰影 X"
L["Shadow Y"] = "陰影 Y"

-- Text fields
L["Text"] = "文字"
L["Texts"] = "文字清單"
L["Add Text"] = "新增文字"
L["Remove"] = "移除"
L["Anchor"] = "錨點"
L["X"] = "X"
L["Y"] = "Y"
L["Tags"] = "標籤"

-- Text tags: bar-relative, name + mouseover description
L["Current Value"] = "目前數值"
L["Max Value"] = "最大數值"
L["Current / Max"] = "目前 / 最大"
L["Percent"] = "百分比"
L["Deficit"] = "缺少值"
L["Current (full)"] = "目前（完整數字）"
L["Max (full)"] = "最大（完整數字）"
L["Current / Max (full)"] = "目前 / 最大（完整數字）"
L["Resource Name"] = "資源名稱"
L["Current value of this bar's resource (short form)."] = "此計量條資源的目前數值（縮寫）。"
L["Maximum value of this bar's resource (short form)."] = "此計量條資源的最大數值（縮寫）。"
L["Current and maximum, shown as cur/max (short form)."] = "目前與最大數值，以 目前/最大 顯示（縮寫）。"
L["Current value as a percentage (0-100%)."] = "目前數值的百分比（0-100%）。"
L["Missing amount (max minus current)."] = "缺少的數量（最大減去目前）。"
L["Current value, full number (not abbreviated)."] = "目前數值，完整數字（不縮寫）。"
L["Maximum value, full number (not abbreviated)."] = "最大數值，完整數字（不縮寫）。"
L["Current and maximum as cur/max, full numbers."] = "目前與最大數值，以 目前/最大 顯示，完整數字。"
L["Name of the resource (e.g. Energy)."] = "資源名稱（例如：能量）。"

-- Text tags: absolute class resources
L["Current number of combo points."] = "目前連擊點數。"
L["Current number of soul shards."] = "目前靈魂裂片數量。"
L["Current holy power."] = "目前聖能。"
L["Current number of Chi."] = "目前真氣數量。"
L["Current number of arcane charges."] = "目前秘法充能層數。"
L["Current number of ready runes."] = "目前可用符文數量。"
L["Current runic power."] = "目前符能。"
L["Current number of essence."] = "目前龍能。"
L["Current insanity."] = "目前瘋狂值。"
L["Current maelstrom."] = "目前元能。"
L["Current astral power."] = "目前星能。"
L["Current fury."] = "目前魔怒。"
L["Current mana."] = "目前法力。"

-- Visibility
L["Visibility"] = "顯示條件"
L["Show"] = "顯示"
L["Always"] = "永遠顯示"
L["Automatic"] = "自動"
L["Never"] = "永不顯示"
L["Custom"] = "自訂"
L["Automatic shows the bar only while its resource is relevant (forms, spec)."] = "自動：僅在該資源有效時顯示計量條（形態、專精）。"
L["The bar shows when any checked condition is true."] = "任一勾選的條件成立時，計量條就會顯示。"
L["Auto-hide all bars while"] = "以下情況自動隱藏所有計量條"
L["In Vehicle"] = "載具中"
L["Pet Battle"] = "寵物對戰中"
L["Blizzard frames"] = "暴雪框架"
L["Hide Blizzard Resource Bars"] = "隱藏暴雪資源條"
L["Hide Blizzard's detached resource bars."] = "隱藏暴雪分離式的資源條。"

-- Visibility condition sections
L["Combat & Target"] = "戰鬥與目標"
L["PvP"] = "PvP"
L["Mount"] = "坐騎"
L["Druid Forms"] = "德魯伊形態"

-- Visibility conditions
L["In Combat"] = "戰鬥中"
L["Has Target"] = "有目標"
L["Hostile Target"] = "敵對目標"
L["Attackable Target"] = "可攻擊目標"
L["Friendly Target"] = "友方目標"
L["Group"] = "隊伍"
L["Instance"] = "副本"
L["In Any Group"] = "任何隊伍中"
L["In Raid Group"] = "團隊中"
L["In Instance"] = "副本中"
L["In Dungeon"] = "地城中"
L["In Raid"] = "團隊副本中"
L["In Battleground"] = "戰場中"
L["In Arena"] = "競技場中"
L["PvP Flagged"] = "PvP 已開啟"
L["War Mode"] = "戰爭模式"
L["Mounted"] = "騎乘中"
L["Flying"] = "飛行中"
L["Cat Form"] = "獵豹形態"
L["Bear Form"] = "熊形態"
L["Moonkin Form"] = "梟獸形態"
L["Travel Form (Stag)"] = "旅行形態（雄鹿）"
L["Aquatic Form"] = "水棲形態"
L["Flight Form"] = "飛行形態"
L["Swift Flight Form"] = "飛行形態（史詩）"
L["Travel Form (Any)"] = "旅行形態（任一）"
L["Humanoid Form"] = "人形態"
